// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKyTucXa_UNETIxx_xxx.Data;

#nullable disable

namespace QuanLyKyTucXa_UNETIxx_xxx.Migrations
{
    [DbContext(typeof(KtxDbContext))]
    [Migration("20260930165944_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.DangKyKTX", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiPhongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiPhongId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("DangKyKTXs");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.LoaiPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaThang")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("LoaiPhongs");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.PhanPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("NgayRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongKTXId")
                        .HasColumnType("int");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhongKTXId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("PhanPhongs");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.PhongKTX", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiPhongId")
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ToaNha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiPhongId");

                    b.ToTable("PhongKTXs");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSV")
                        .IsUnique();

                    b.HasIndex("TaiKhoanId")
                        .IsUnique();

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.DangKyKTX", b =>
                {
                    b.HasOne("QuanLyKyTucXa_UNETIxx_xxx.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("LoaiPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKyTucXa_UNETIxx_xxx.Models.SinhVien", "SinhVien")
                        .WithMany("DangKys")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.PhanPhong", b =>
                {
                    b.HasOne("QuanLyKyTucXa_UNETIxx_xxx.Models.PhongKTX", "PhongKTX")
                        .WithMany("PhanPhongs")
                        .HasForeignKey("PhongKTXId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKyTucXa_UNETIxx_xxx.Models.SinhVien", "SinhVien")
                        .WithMany("PhanPhongs")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongKTX");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.PhongKTX", b =>
                {
                    b.HasOne("QuanLyKyTucXa_UNETIxx_xxx.Models.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("LoaiPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.SinhVien", b =>
                {
                    b.HasOne("QuanLyKyTucXa_UNETIxx_xxx.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("SinhVien")
                        .HasForeignKey("QuanLyKyTucXa_UNETIxx_xxx.Models.SinhVien", "TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.PhongKTX", b =>
                {
                    b.Navigation("PhanPhongs");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.SinhVien", b =>
                {
                    b.Navigation("DangKys");

                    b.Navigation("PhanPhongs");
                });

            modelBuilder.Entity("QuanLyKyTucXa_UNETIxx_xxx.Models.TaiKhoan", b =>
                {
                    b.Navigation("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
